# Generated by Django 3.2.16 on 2025-02-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250121_1311'),
        ('blog', '0004_remove_comment_updated_at'),
    ]

    operations = [
    ]
